name: Deploy server test
on:
  push:
    branches: [ "main", ]

jobs:
  deploy1:
    strategy:
      matrix:
        server-list: [Qlaster, testDB]
    
    runs-on: 
    - ${{ matrix.server-list }}
    - self-hosted
    steps: 
      - name: cd into repo 
        uses: actions/checkout@v3 
      - name: update repo2
        run: cd /opt/server_monitoring && git pull

