name: Deploy server test
on:
  push:
    branches: [ "main", ]
  
jobs:
  deploy:
    runs-on: [self-hosted, testDB]
    steps: 
      - name: cd into repo 
        uses: actions/checkout@v3 
      - name: update repo
        run: cd /opt/server_monitoring && git pull

